/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrandingConfig {
  'color' : string,
  'enabled' : boolean,
  'logoUrl' : string,
  'fontFamily' : string,
  'photographerName' : string,
  'fontSize' : bigint,
  'positionX' : number,
  'positionY' : number,
  'opacity' : number,
}
export interface EventMode {
  'activeTemplateId' : [] | [string],
  'activeFilterPresetId' : [] | [string],
  'isLocked' : boolean,
}
export interface FilterPreset {
  'id' : string,
  'exposure' : number,
  'sharpness' : number,
  'vignette' : number,
  'contrast' : number,
  'temperature' : number,
  'fade' : number,
  'name' : string,
  'createdAt' : Time,
  'tint' : number,
  'shadows' : number,
  'highlights' : number,
  'grain' : number,
}
export interface Session {
  'id' : string,
  'date' : Time,
  'createdAt' : Time,
  'photoCount' : bigint,
  'layoutType' : string,
  'eventName' : string,
}
export interface Template {
  'id' : string,
  'schemaJson' : string,
  'name' : string,
  'createdAt' : Time,
  'layoutType' : string,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createFilterPreset' : ActorMethod<
    [
      string,
      string,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
    ],
    undefined
  >,
  'createSession' : ActorMethod<
    [string, string, Time, string, bigint],
    undefined
  >,
  'createTemplate' : ActorMethod<[string, string, string, string], undefined>,
  'getAllFilterPresets' : ActorMethod<[], Array<FilterPreset>>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getAllTemplates' : ActorMethod<[], Array<Template>>,
  'getBrandingConfig' : ActorMethod<[], [] | [BrandingConfig]>,
  'getEventMode' : ActorMethod<[], EventMode>,
  'getFilterPreset' : ActorMethod<[string], FilterPreset>,
  'getSession' : ActorMethod<[string], Session>,
  'getTemplate' : ActorMethod<[string], Template>,
  'setBrandingConfig' : ActorMethod<[BrandingConfig], undefined>,
  'setEventMode' : ActorMethod<
    [boolean, [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];