/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const FilterPreset = IDL.Record({
  'id' : IDL.Text,
  'exposure' : IDL.Float64,
  'sharpness' : IDL.Float64,
  'vignette' : IDL.Float64,
  'contrast' : IDL.Float64,
  'temperature' : IDL.Float64,
  'fade' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : Time,
  'tint' : IDL.Float64,
  'shadows' : IDL.Float64,
  'highlights' : IDL.Float64,
  'grain' : IDL.Float64,
});
export const Session = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'createdAt' : Time,
  'photoCount' : IDL.Nat,
  'layoutType' : IDL.Text,
  'eventName' : IDL.Text,
});
export const Template = IDL.Record({
  'id' : IDL.Text,
  'schemaJson' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'layoutType' : IDL.Text,
});
export const BrandingConfig = IDL.Record({
  'color' : IDL.Text,
  'enabled' : IDL.Bool,
  'logoUrl' : IDL.Text,
  'fontFamily' : IDL.Text,
  'photographerName' : IDL.Text,
  'fontSize' : IDL.Nat,
  'positionX' : IDL.Float64,
  'positionY' : IDL.Float64,
  'opacity' : IDL.Float64,
});
export const EventMode = IDL.Record({
  'activeTemplateId' : IDL.Opt(IDL.Text),
  'activeFilterPresetId' : IDL.Opt(IDL.Text),
  'isLocked' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createFilterPreset' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'createSession' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createTemplate' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllFilterPresets' : IDL.Func([], [IDL.Vec(FilterPreset)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'getBrandingConfig' : IDL.Func([], [IDL.Opt(BrandingConfig)], ['query']),
  'getEventMode' : IDL.Func([], [EventMode], ['query']),
  'getFilterPreset' : IDL.Func([IDL.Text], [FilterPreset], ['query']),
  'getSession' : IDL.Func([IDL.Text], [Session], ['query']),
  'getTemplate' : IDL.Func([IDL.Text], [Template], ['query']),
  'setBrandingConfig' : IDL.Func([BrandingConfig], [], []),
  'setEventMode' : IDL.Func(
      [IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const FilterPreset = IDL.Record({
    'id' : IDL.Text,
    'exposure' : IDL.Float64,
    'sharpness' : IDL.Float64,
    'vignette' : IDL.Float64,
    'contrast' : IDL.Float64,
    'temperature' : IDL.Float64,
    'fade' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : Time,
    'tint' : IDL.Float64,
    'shadows' : IDL.Float64,
    'highlights' : IDL.Float64,
    'grain' : IDL.Float64,
  });
  const Session = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'createdAt' : Time,
    'photoCount' : IDL.Nat,
    'layoutType' : IDL.Text,
    'eventName' : IDL.Text,
  });
  const Template = IDL.Record({
    'id' : IDL.Text,
    'schemaJson' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'layoutType' : IDL.Text,
  });
  const BrandingConfig = IDL.Record({
    'color' : IDL.Text,
    'enabled' : IDL.Bool,
    'logoUrl' : IDL.Text,
    'fontFamily' : IDL.Text,
    'photographerName' : IDL.Text,
    'fontSize' : IDL.Nat,
    'positionX' : IDL.Float64,
    'positionY' : IDL.Float64,
    'opacity' : IDL.Float64,
  });
  const EventMode = IDL.Record({
    'activeTemplateId' : IDL.Opt(IDL.Text),
    'activeFilterPresetId' : IDL.Opt(IDL.Text),
    'isLocked' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createFilterPreset' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'createSession' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllFilterPresets' : IDL.Func([], [IDL.Vec(FilterPreset)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'getBrandingConfig' : IDL.Func([], [IDL.Opt(BrandingConfig)], ['query']),
    'getEventMode' : IDL.Func([], [EventMode], ['query']),
    'getFilterPreset' : IDL.Func([IDL.Text], [FilterPreset], ['query']),
    'getSession' : IDL.Func([IDL.Text], [Session], ['query']),
    'getTemplate' : IDL.Func([IDL.Text], [Template], ['query']),
    'setBrandingConfig' : IDL.Func([BrandingConfig], [], []),
    'setEventMode' : IDL.Func(
        [IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };